//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 03:10:19 pm IST 
//


package com.demandware.xml.impex.customer._2006_10_31;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Header complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Header">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.4000" minOccurs="0"/>
 *         &lt;element name="data-retention-days" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="customerno-sequence-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="customer-lockout-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="max-failed-logins" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="lockout-effective-period" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="customer-login-attempt-reset-time" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="min-password-length" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="min-password-special-chars" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="force-password-contains-alpha" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="force-password-contains-numeric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="force-password-mixed-case" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="max-password-age" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max-password-reset-token-age" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Header", propOrder = {
    "description",
    "dataRetentionDays",
    "customernoSequenceEnabled",
    "customerLockoutEnabled",
    "maxFailedLogins",
    "lockoutEffectivePeriod",
    "customerLoginAttemptResetTime",
    "minPasswordLength",
    "minPasswordSpecialChars",
    "forcePasswordContainsAlpha",
    "forcePasswordContainsNumeric",
    "forcePasswordMixedCase",
    "maxPasswordAge",
    "maxPasswordResetTokenAge"
})
public class ComplexTypeHeader {

    protected String description;
    @XmlElement(name = "data-retention-days")
    protected BigInteger dataRetentionDays;
    @XmlElement(name = "customerno-sequence-enabled")
    protected Boolean customernoSequenceEnabled;
    @XmlElement(name = "customer-lockout-enabled")
    protected Boolean customerLockoutEnabled;
    @XmlElement(name = "max-failed-logins")
    protected BigInteger maxFailedLogins;
    @XmlElement(name = "lockout-effective-period")
    protected BigInteger lockoutEffectivePeriod;
    @XmlElement(name = "customer-login-attempt-reset-time")
    protected BigInteger customerLoginAttemptResetTime;
    @XmlElement(name = "min-password-length")
    protected BigInteger minPasswordLength;
    @XmlElement(name = "min-password-special-chars")
    protected BigInteger minPasswordSpecialChars;
    @XmlElement(name = "force-password-contains-alpha")
    protected Boolean forcePasswordContainsAlpha;
    @XmlElement(name = "force-password-contains-numeric")
    protected Boolean forcePasswordContainsNumeric;
    @XmlElement(name = "force-password-mixed-case")
    protected Boolean forcePasswordMixedCase;
    @XmlElement(name = "max-password-age")
    protected BigInteger maxPasswordAge;
    @XmlElement(name = "max-password-reset-token-age")
    protected BigInteger maxPasswordResetTokenAge;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dataRetentionDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataRetentionDays() {
        return dataRetentionDays;
    }

    /**
     * Sets the value of the dataRetentionDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataRetentionDays(BigInteger value) {
        this.dataRetentionDays = value;
    }

    /**
     * Gets the value of the customernoSequenceEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomernoSequenceEnabled() {
        return customernoSequenceEnabled;
    }

    /**
     * Sets the value of the customernoSequenceEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomernoSequenceEnabled(Boolean value) {
        this.customernoSequenceEnabled = value;
    }

    /**
     * Gets the value of the customerLockoutEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomerLockoutEnabled() {
        return customerLockoutEnabled;
    }

    /**
     * Sets the value of the customerLockoutEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomerLockoutEnabled(Boolean value) {
        this.customerLockoutEnabled = value;
    }

    /**
     * Gets the value of the maxFailedLogins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxFailedLogins() {
        return maxFailedLogins;
    }

    /**
     * Sets the value of the maxFailedLogins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxFailedLogins(BigInteger value) {
        this.maxFailedLogins = value;
    }

    /**
     * Gets the value of the lockoutEffectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLockoutEffectivePeriod() {
        return lockoutEffectivePeriod;
    }

    /**
     * Sets the value of the lockoutEffectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLockoutEffectivePeriod(BigInteger value) {
        this.lockoutEffectivePeriod = value;
    }

    /**
     * Gets the value of the customerLoginAttemptResetTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerLoginAttemptResetTime() {
        return customerLoginAttemptResetTime;
    }

    /**
     * Sets the value of the customerLoginAttemptResetTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerLoginAttemptResetTime(BigInteger value) {
        this.customerLoginAttemptResetTime = value;
    }

    /**
     * Gets the value of the minPasswordLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinPasswordLength() {
        return minPasswordLength;
    }

    /**
     * Sets the value of the minPasswordLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinPasswordLength(BigInteger value) {
        this.minPasswordLength = value;
    }

    /**
     * Gets the value of the minPasswordSpecialChars property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinPasswordSpecialChars() {
        return minPasswordSpecialChars;
    }

    /**
     * Sets the value of the minPasswordSpecialChars property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinPasswordSpecialChars(BigInteger value) {
        this.minPasswordSpecialChars = value;
    }

    /**
     * Gets the value of the forcePasswordContainsAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForcePasswordContainsAlpha() {
        return forcePasswordContainsAlpha;
    }

    /**
     * Sets the value of the forcePasswordContainsAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForcePasswordContainsAlpha(Boolean value) {
        this.forcePasswordContainsAlpha = value;
    }

    /**
     * Gets the value of the forcePasswordContainsNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForcePasswordContainsNumeric() {
        return forcePasswordContainsNumeric;
    }

    /**
     * Sets the value of the forcePasswordContainsNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForcePasswordContainsNumeric(Boolean value) {
        this.forcePasswordContainsNumeric = value;
    }

    /**
     * Gets the value of the forcePasswordMixedCase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForcePasswordMixedCase() {
        return forcePasswordMixedCase;
    }

    /**
     * Sets the value of the forcePasswordMixedCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForcePasswordMixedCase(Boolean value) {
        this.forcePasswordMixedCase = value;
    }

    /**
     * Gets the value of the maxPasswordAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPasswordAge() {
        return maxPasswordAge;
    }

    /**
     * Sets the value of the maxPasswordAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPasswordAge(BigInteger value) {
        this.maxPasswordAge = value;
    }

    /**
     * Gets the value of the maxPasswordResetTokenAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPasswordResetTokenAge() {
        return maxPasswordResetTokenAge;
    }

    /**
     * Sets the value of the maxPasswordResetTokenAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPasswordResetTokenAge(BigInteger value) {
        this.maxPasswordResetTokenAge = value;
    }

}
