//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 03:10:19 pm IST 
//


package com.demandware.xml.impex.customer._2006_10_31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 *             Represents an encrypted or plain value and contains information on how to deal with it during import.
 *             
 *             Import: If the attribute 'encrypted' is set to false, the content of this tag will be encrypted  
 *             using the new scrypt algorithm. 'encryptionScheme' should be 'null' in this case.
 *             If the attribute 'encrypted' is set to true, it is assumed that the given password was encrypted
 *             with the algorithm in 'encryptionScheme' (md5, scrypt, or the internal implementation s0001). 
 *             The password will be imported 'as is'.
 *             
 *             Export: The attribute 'encrypted' will always be set to true. The attribute 'encryptionScheme'
 *             will reflect the encryption scheme of the password in the database (md5 (deprecated), scrypt, or the internal implementation s0001). 
 *             The encrypted password will not be transformed during export.
 *             
 * 
 * <p>Java class for complexType.Password complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Password">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.demandware.com/xml/impex/customer/2006-10-31>simpleType.Generic.String.256">
 *       &lt;attribute name="encrypted" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="encryptionScheme" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.EncryptionScheme" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Password", propOrder = {
    "value"
})
public class ComplexTypePassword {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "encrypted", required = true)
    protected boolean encrypted;
    @XmlAttribute(name = "encryptionScheme")
    protected SimpleTypeEncryptionScheme encryptionScheme;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the encrypted property.
     * 
     */
    public boolean isEncrypted() {
        return encrypted;
    }

    /**
     * Sets the value of the encrypted property.
     * 
     */
    public void setEncrypted(boolean value) {
        this.encrypted = value;
    }

    /**
     * Gets the value of the encryptionScheme property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeEncryptionScheme }
     *     
     */
    public SimpleTypeEncryptionScheme getEncryptionScheme() {
        return encryptionScheme;
    }

    /**
     * Sets the value of the encryptionScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeEncryptionScheme }
     *     
     */
    public void setEncryptionScheme(SimpleTypeEncryptionScheme value) {
        this.encryptionScheme = value;
    }

}
