//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 03:10:19 pm IST 
//


package com.demandware.xml.impex.customer._2006_10_31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for complexType.Profile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="salutation" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="first-name" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="second-name" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="last-name" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="suffix" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="company-name" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="job-title" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Email" minOccurs="0"/>
 *         &lt;element name="phone-home" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="phone-business" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="phone-mobile" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Gender" minOccurs="0"/>
 *         &lt;element name="creation-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="last-login-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="last-visit-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="preferred-locale" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.10" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Profile", propOrder = {
    "salutation",
    "title",
    "firstName",
    "secondName",
    "lastName",
    "suffix",
    "companyName",
    "jobTitle",
    "email",
    "phoneHome",
    "phoneBusiness",
    "phoneMobile",
    "fax",
    "birthday",
    "gender",
    "creationDate",
    "lastLoginTime",
    "lastVisitTime",
    "preferredLocale",
    "customAttributes"
})
public class ComplexTypeProfile {

    protected String salutation;
    protected String title;
    @XmlElement(name = "first-name")
    protected String firstName;
    @XmlElement(name = "second-name")
    protected String secondName;
    @XmlElement(name = "last-name")
    protected String lastName;
    protected String suffix;
    @XmlElement(name = "company-name")
    protected String companyName;
    @XmlElement(name = "job-title")
    protected String jobTitle;
    protected String email;
    @XmlElement(name = "phone-home")
    protected String phoneHome;
    @XmlElement(name = "phone-business")
    protected String phoneBusiness;
    @XmlElement(name = "phone-mobile")
    protected String phoneMobile;
    protected String fax;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthday;
    protected String gender;
    @XmlElement(name = "creation-date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(name = "last-login-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastLoginTime;
    @XmlElement(name = "last-visit-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastVisitTime;
    @XmlElement(name = "preferred-locale")
    protected String preferredLocale;
    @XmlElement(name = "custom-attributes")
    protected SharedTypeCustomAttributes customAttributes;

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the secondName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondName() {
        return secondName;
    }

    /**
     * Sets the value of the secondName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondName(String value) {
        this.secondName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phoneHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneHome() {
        return phoneHome;
    }

    /**
     * Sets the value of the phoneHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneHome(String value) {
        this.phoneHome = value;
    }

    /**
     * Gets the value of the phoneBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneBusiness() {
        return phoneBusiness;
    }

    /**
     * Sets the value of the phoneBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneBusiness(String value) {
        this.phoneBusiness = value;
    }

    /**
     * Gets the value of the phoneMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneMobile() {
        return phoneMobile;
    }

    /**
     * Sets the value of the phoneMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneMobile(String value) {
        this.phoneMobile = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthday(XMLGregorianCalendar value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the lastLoginTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * Sets the value of the lastLoginTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastLoginTime(XMLGregorianCalendar value) {
        this.lastLoginTime = value;
    }

    /**
     * Gets the value of the lastVisitTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastVisitTime() {
        return lastVisitTime;
    }

    /**
     * Sets the value of the lastVisitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastVisitTime(XMLGregorianCalendar value) {
        this.lastVisitTime = value;
    }

    /**
     * Gets the value of the preferredLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLocale() {
        return preferredLocale;
    }

    /**
     * Sets the value of the preferredLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLocale(String value) {
        this.preferredLocale = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

}
