//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 03:10:19 pm IST 
//


package com.demandware.xml.impex.customer._2006_10_31;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demandware.xml.impex.customer._2006_10_31 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Header_QNAME = new QName("http://www.demandware.com/xml/impex/customer/2006-10-31", "header");
    private final static QName _Customer_QNAME = new QName("http://www.demandware.com/xml/impex/customer/2006-10-31", "customer");
    private final static QName _GroupAssignment_QNAME = new QName("http://www.demandware.com/xml/impex/customer/2006-10-31", "group-assignment");
    private final static QName _SharedTypeCustomAttributeValue_QNAME = new QName("http://www.demandware.com/xml/impex/customer/2006-10-31", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demandware.xml.impex.customer._2006_10_31
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerList }
     * 
     */
    public CustomerList createCustomerList() {
        return new CustomerList();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttribute }
     * 
     */
    public SharedTypeCustomAttribute createSharedTypeCustomAttribute() {
        return new SharedTypeCustomAttribute();
    }

    /**
     * Create an instance of {@link ComplexTypeAddress }
     * 
     */
    public ComplexTypeAddress createComplexTypeAddress() {
        return new ComplexTypeAddress();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomer }
     * 
     */
    public ComplexTypeCustomer createComplexTypeCustomer() {
        return new ComplexTypeCustomer();
    }

    /**
     * Create an instance of {@link ComplexTypeHeader }
     * 
     */
    public ComplexTypeHeader createComplexTypeHeader() {
        return new ComplexTypeHeader();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomerGroup }
     * 
     */
    public ComplexTypeCustomerGroup createComplexTypeCustomerGroup() {
        return new ComplexTypeCustomerGroup();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomerGroups }
     * 
     */
    public ComplexTypeCustomerGroups createComplexTypeCustomerGroups() {
        return new ComplexTypeCustomerGroups();
    }

    /**
     * Create an instance of {@link ComplexTypeExternalProfile }
     * 
     */
    public ComplexTypeExternalProfile createComplexTypeExternalProfile() {
        return new ComplexTypeExternalProfile();
    }

    /**
     * Create an instance of {@link ComplexTypeExternalProfiles }
     * 
     */
    public ComplexTypeExternalProfiles createComplexTypeExternalProfiles() {
        return new ComplexTypeExternalProfiles();
    }

    /**
     * Create an instance of {@link ComplexTypeAddresses }
     * 
     */
    public ComplexTypeAddresses createComplexTypeAddresses() {
        return new ComplexTypeAddresses();
    }

    /**
     * Create an instance of {@link ComplexTypePassword }
     * 
     */
    public ComplexTypePassword createComplexTypePassword() {
        return new ComplexTypePassword();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomerGroupAssignment }
     * 
     */
    public ComplexTypeCustomerGroupAssignment createComplexTypeCustomerGroupAssignment() {
        return new ComplexTypeCustomerGroupAssignment();
    }

    /**
     * Create an instance of {@link ComplexTypeProfile }
     * 
     */
    public ComplexTypeProfile createComplexTypeProfile() {
        return new ComplexTypeProfile();
    }

    /**
     * Create an instance of {@link ComplexTypeCredentials }
     * 
     */
    public ComplexTypeCredentials createComplexTypeCredentials() {
        return new ComplexTypeCredentials();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttributes }
     * 
     */
    public SharedTypeCustomAttributes createSharedTypeCustomAttributes() {
        return new SharedTypeCustomAttributes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", name = "header")
    public JAXBElement<ComplexTypeHeader> createHeader(ComplexTypeHeader value) {
        return new JAXBElement<ComplexTypeHeader>(_Header_QNAME, ComplexTypeHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", name = "customer")
    public JAXBElement<ComplexTypeCustomer> createCustomer(ComplexTypeCustomer value) {
        return new JAXBElement<ComplexTypeCustomer>(_Customer_QNAME, ComplexTypeCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeCustomerGroupAssignment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", name = "group-assignment")
    public JAXBElement<ComplexTypeCustomerGroupAssignment> createGroupAssignment(ComplexTypeCustomerGroupAssignment value) {
        return new JAXBElement<ComplexTypeCustomerGroupAssignment>(_GroupAssignment_QNAME, ComplexTypeCustomerGroupAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", name = "value", scope = SharedTypeCustomAttribute.class)
    public JAXBElement<String> createSharedTypeCustomAttributeValue(String value) {
        return new JAXBElement<String>(_SharedTypeCustomAttributeValue_QNAME, String.class, SharedTypeCustomAttribute.class, value);
    }

}
