//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.27 at 12:34:45 pm IST 
//


package com.demandware.xml.impex.customerlist._2010_06_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demandware.xml.impex.customerlist._2010_06_30 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerList_QNAME = new QName("http://www.demandware.com/xml/impex/customerlist/2010-06-30", "customer-list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demandware.xml.impex.customerlist._2010_06_30
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerLists }
     * 
     */
    public CustomerLists createCustomerLists() {
        return new CustomerLists();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomerList }
     * 
     */
    public ComplexTypeCustomerList createComplexTypeCustomerList() {
        return new ComplexTypeCustomerList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeCustomerList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customerlist/2010-06-30", name = "customer-list")
    public JAXBElement<ComplexTypeCustomerList> createCustomerList(ComplexTypeCustomerList value) {
        return new JAXBElement<ComplexTypeCustomerList>(_CustomerList_QNAME, ComplexTypeCustomerList.class, null, value);
    }

}
