//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.27 at 12:34:45 pm IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demandware.com/xml/impex/customerlist/2010-06-30", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demandware.xml.impex.customerlist._2010_06_30;
