//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Header" minOccurs="0"/>
 *         &lt;element name="product-attribute-definitions" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.AttributeDefinitions" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Category" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="product" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="product-option" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variation-attribute" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.VariationAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="category-assignment" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.CategoryAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="recommendation" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Recommendation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="catalog-id" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "productAttributeDefinitions",
    "category",
    "product",
    "productOption",
    "variationAttribute",
    "categoryAssignment",
    "recommendation"
})
@XmlRootElement(name = "catalog")
public class Catalog {

    protected ComplexTypeHeader header;
    @XmlElement(name = "product-attribute-definitions")
    protected ComplexTypeAttributeDefinitions productAttributeDefinitions;
    protected List<ComplexTypeCategory> category;
    protected List<ComplexTypeProduct> product;
    @XmlElement(name = "product-option")
    protected List<ComplexTypeOption> productOption;
    @XmlElement(name = "variation-attribute")
    protected List<ComplexTypeVariationAttribute> variationAttribute;
    @XmlElement(name = "category-assignment")
    protected List<ComplexTypeCategoryAssignment> categoryAssignment;
    protected List<ComplexTypeRecommendation> recommendation;
    @XmlAttribute(name = "catalog-id", required = true)
    protected String catalogId;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeHeader }
     *     
     */
    public ComplexTypeHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeHeader }
     *     
     */
    public void setHeader(ComplexTypeHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the productAttributeDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeAttributeDefinitions }
     *     
     */
    public ComplexTypeAttributeDefinitions getProductAttributeDefinitions() {
        return productAttributeDefinitions;
    }

    /**
     * Sets the value of the productAttributeDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeAttributeDefinitions }
     *     
     */
    public void setProductAttributeDefinitions(ComplexTypeAttributeDefinitions value) {
        this.productAttributeDefinitions = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeCategory }
     * 
     * 
     */
    public List<ComplexTypeCategory> getCategory() {
        if (category == null) {
            category = new ArrayList<ComplexTypeCategory>();
        }
        return this.category;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProduct }
     * 
     * 
     */
    public List<ComplexTypeProduct> getProduct() {
        if (product == null) {
            product = new ArrayList<ComplexTypeProduct>();
        }
        return this.product;
    }

    /**
     * Gets the value of the productOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeOption }
     * 
     * 
     */
    public List<ComplexTypeOption> getProductOption() {
        if (productOption == null) {
            productOption = new ArrayList<ComplexTypeOption>();
        }
        return this.productOption;
    }

    /**
     * Gets the value of the variationAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variationAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariationAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeVariationAttribute }
     * 
     * 
     */
    public List<ComplexTypeVariationAttribute> getVariationAttribute() {
        if (variationAttribute == null) {
            variationAttribute = new ArrayList<ComplexTypeVariationAttribute>();
        }
        return this.variationAttribute;
    }

    /**
     * Gets the value of the categoryAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeCategoryAssignment }
     * 
     * 
     */
    public List<ComplexTypeCategoryAssignment> getCategoryAssignment() {
        if (categoryAssignment == null) {
            categoryAssignment = new ArrayList<ComplexTypeCategoryAssignment>();
        }
        return this.categoryAssignment;
    }

    /**
     * Gets the value of the recommendation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recommendation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecommendation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeRecommendation }
     * 
     * 
     */
    public List<ComplexTypeRecommendation> getRecommendation() {
        if (recommendation == null) {
            recommendation = new ArrayList<ComplexTypeRecommendation>();
        }
        return this.recommendation;
    }

    /**
     * Gets the value of the catalogId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * Sets the value of the catalogId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogId(String value) {
        this.catalogId = value;
    }

}
