//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product.ProductSetProducts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.ProductSetProducts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="product-set-product" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.ProductSetProduct" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.ProductSetProducts", propOrder = {
    "productSetProduct"
})
public class ComplexTypeProductProductSetProducts {

    @XmlElement(name = "product-set-product")
    protected List<ComplexTypeProductProductSetProduct> productSetProduct;

    /**
     * Gets the value of the productSetProduct property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productSetProduct property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSetProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProductProductSetProduct }
     * 
     * 
     */
    public List<ComplexTypeProductProductSetProduct> getProductSetProduct() {
        if (productSetProduct == null) {
            productSetProduct = new ArrayList<ComplexTypeProductProductSetProduct>();
        }
        return this.productSetProduct;
    }

}
