//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Option complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Option">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="display-name" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="sort-mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Option.SortMode" minOccurs="0"/>
 *         &lt;element name="option-values" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Option.Values" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.ImportMode" />
 *       &lt;attribute name="option-id" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Option", propOrder = {
    "displayName",
    "description",
    "image",
    "sortMode",
    "optionValues"
})
public class ComplexTypeOption {

    @XmlElement(name = "display-name")
    protected List<SharedTypeLocalizedString> displayName;
    protected List<SharedTypeLocalizedString> description;
    protected String image;
    @XmlElement(name = "sort-mode")
    protected SimpleTypeOptionSortMode sortMode;
    @XmlElement(name = "option-values")
    protected ComplexTypeOptionValues optionValues;
    @XmlAttribute(name = "mode")
    protected SimpleTypeImportMode mode;
    @XmlAttribute(name = "option-id", required = true)
    protected String optionId;

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedString }
     * 
     * 
     */
    public List<SharedTypeLocalizedString> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<SharedTypeLocalizedString>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedString }
     * 
     * 
     */
    public List<SharedTypeLocalizedString> getDescription() {
        if (description == null) {
            description = new ArrayList<SharedTypeLocalizedString>();
        }
        return this.description;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the sortMode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOptionSortMode }
     *     
     */
    public SimpleTypeOptionSortMode getSortMode() {
        return sortMode;
    }

    /**
     * Sets the value of the sortMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOptionSortMode }
     *     
     */
    public void setSortMode(SimpleTypeOptionSortMode value) {
        this.sortMode = value;
    }

    /**
     * Gets the value of the optionValues property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeOptionValues }
     *     
     */
    public ComplexTypeOptionValues getOptionValues() {
        return optionValues;
    }

    /**
     * Sets the value of the optionValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeOptionValues }
     *     
     */
    public void setOptionValues(ComplexTypeOptionValues value) {
        this.optionValues = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public SimpleTypeImportMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public void setMode(SimpleTypeImportMode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the optionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * Sets the value of the optionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionId(String value) {
        this.optionId = value;
    }

}
