//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reserved for Beta users. Variation groups will not be created and a warning will be logged if the Variation Groups (Beta) feature is disabled.
 * 
 * <p>Java class for complexType.Product.Variations.VariationGroups complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.Variations.VariationGroups">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="variation-group" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations.VariationGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="merge-mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.MergeMode" default="replace" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.Variations.VariationGroups", propOrder = {
    "variationGroup"
})
public class ComplexTypeProductVariationsVariationGroups {

    @XmlElement(name = "variation-group")
    protected List<ComplexTypeProductVariationsVariationGroup> variationGroup;
    @XmlAttribute(name = "merge-mode")
    protected SimpleTypeMergeMode mergeMode;

    /**
     * Gets the value of the variationGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variationGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariationGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProductVariationsVariationGroup }
     * 
     * 
     */
    public List<ComplexTypeProductVariationsVariationGroup> getVariationGroup() {
        if (variationGroup == null) {
            variationGroup = new ArrayList<ComplexTypeProductVariationsVariationGroup>();
        }
        return this.variationGroup;
    }

    /**
     * Gets the value of the mergeMode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeMergeMode }
     *     
     */
    public SimpleTypeMergeMode getMergeMode() {
        if (mergeMode == null) {
            return SimpleTypeMergeMode.REPLACE;
        } else {
            return mergeMode;
        }
    }

    /**
     * Sets the value of the mergeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeMergeMode }
     *     
     */
    public void setMergeMode(SimpleTypeMergeMode value) {
        this.mergeMode = value;
    }

}
