//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product.StoreAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.StoreAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receipt-name" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tax-class" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.60" minOccurs="0"/>
 *         &lt;element name="force-price-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="non-inventory-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="non-revenue-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="non-discountable-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.StoreAttributes", propOrder = {
    "receiptName",
    "taxClass",
    "forcePriceFlag",
    "nonInventoryFlag",
    "nonRevenueFlag",
    "nonDiscountableFlag"
})
public class ComplexTypeProductStoreAttributes {

    @XmlElement(name = "receipt-name")
    protected List<SharedTypeLocalizedText> receiptName;
    @XmlElement(name = "tax-class")
    protected String taxClass;
    @XmlElement(name = "force-price-flag")
    protected Boolean forcePriceFlag;
    @XmlElement(name = "non-inventory-flag")
    protected Boolean nonInventoryFlag;
    @XmlElement(name = "non-revenue-flag")
    protected Boolean nonRevenueFlag;
    @XmlElement(name = "non-discountable-flag")
    protected Boolean nonDiscountableFlag;

    /**
     * Gets the value of the receiptName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receiptName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceiptName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedText }
     * 
     * 
     */
    public List<SharedTypeLocalizedText> getReceiptName() {
        if (receiptName == null) {
            receiptName = new ArrayList<SharedTypeLocalizedText>();
        }
        return this.receiptName;
    }

    /**
     * Gets the value of the taxClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxClass() {
        return taxClass;
    }

    /**
     * Sets the value of the taxClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxClass(String value) {
        this.taxClass = value;
    }

    /**
     * Gets the value of the forcePriceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForcePriceFlag() {
        return forcePriceFlag;
    }

    /**
     * Sets the value of the forcePriceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForcePriceFlag(Boolean value) {
        this.forcePriceFlag = value;
    }

    /**
     * Gets the value of the nonInventoryFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNonInventoryFlag() {
        return nonInventoryFlag;
    }

    /**
     * Sets the value of the nonInventoryFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonInventoryFlag(Boolean value) {
        this.nonInventoryFlag = value;
    }

    /**
     * Gets the value of the nonRevenueFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNonRevenueFlag() {
        return nonRevenueFlag;
    }

    /**
     * Sets the value of the nonRevenueFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonRevenueFlag(Boolean value) {
        this.nonRevenueFlag = value;
    }

    /**
     * Gets the value of the nonDiscountableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNonDiscountableFlag() {
        return nonDiscountableFlag;
    }

    /**
     * Sets the value of the nonDiscountableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonDiscountableFlag(Boolean value) {
        this.nonDiscountableFlag = value;
    }

}
