//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.CategoryAssignment.VariationAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.CategoryAssignment.VariationAssignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="variation-assignment-values" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.CategoryAssignment.VariationAssignment.Values" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="variation-attribute-id" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *       &lt;attribute name="slicing-attribute" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.CategoryAssignment.VariationAssignment", propOrder = {
    "variationAssignmentValues"
})
public class ComplexTypeCategoryAssignmentVariationAssignment {

    @XmlElement(name = "variation-assignment-values")
    protected ComplexTypeCategoryAssignmentVariationAssignmentValues variationAssignmentValues;
    @XmlAttribute(name = "variation-attribute-id", required = true)
    protected String variationAttributeId;
    @XmlAttribute(name = "slicing-attribute")
    protected Boolean slicingAttribute;

    /**
     * Gets the value of the variationAssignmentValues property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCategoryAssignmentVariationAssignmentValues }
     *     
     */
    public ComplexTypeCategoryAssignmentVariationAssignmentValues getVariationAssignmentValues() {
        return variationAssignmentValues;
    }

    /**
     * Sets the value of the variationAssignmentValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCategoryAssignmentVariationAssignmentValues }
     *     
     */
    public void setVariationAssignmentValues(ComplexTypeCategoryAssignmentVariationAssignmentValues value) {
        this.variationAssignmentValues = value;
    }

    /**
     * Gets the value of the variationAttributeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariationAttributeId() {
        return variationAttributeId;
    }

    /**
     * Sets the value of the variationAttributeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariationAttributeId(String value) {
        this.variationAttributeId = value;
    }

    /**
     * Gets the value of the slicingAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSlicingAttribute() {
        return slicingAttribute;
    }

    /**
     * Sets the value of the slicingAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSlicingAttribute(Boolean value) {
        this.slicingAttribute = value;
    }

}
