//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.RefinementDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.RefinementDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="display-name" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="value-set" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Refinement.ValueSet" minOccurs="0"/>
 *         &lt;element name="sort-mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Sorting.Mode" minOccurs="0"/>
 *         &lt;element name="sort-direction" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Sorting.Direction" minOccurs="0"/>
 *         &lt;element name="unbucketed-values-mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.UnbucketedValues.Mode" minOccurs="0"/>
 *         &lt;element name="cutoff-threshold" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="bucket-definitions" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.RefinementBuckets" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Refinement.Type" />
 *       &lt;attribute name="bucket-type" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Bucket.Type" />
 *       &lt;attribute name="attribute-id" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *       &lt;attribute name="system" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.RefinementDefinition", propOrder = {
    "displayName",
    "valueSet",
    "sortMode",
    "sortDirection",
    "unbucketedValuesMode",
    "cutoffThreshold",
    "bucketDefinitions"
})
public class ComplexTypeRefinementDefinition {

    @XmlElement(name = "display-name")
    protected List<SharedTypeLocalizedString> displayName;
    @XmlElement(name = "value-set")
    protected SimpleTypeRefinementValueSet valueSet;
    @XmlElement(name = "sort-mode")
    protected SimpleTypeSortingMode sortMode;
    @XmlElement(name = "sort-direction")
    protected SimpleTypeSortingDirection sortDirection;
    @XmlElement(name = "unbucketed-values-mode")
    protected SimpleTypeUnbucketedValuesMode unbucketedValuesMode;
    @XmlElement(name = "cutoff-threshold")
    protected Integer cutoffThreshold;
    @XmlElement(name = "bucket-definitions")
    protected ComplexTypeRefinementBuckets bucketDefinitions;
    @XmlAttribute(name = "type", required = true)
    protected SimpleTypeRefinementType type;
    @XmlAttribute(name = "bucket-type")
    protected SimpleTypeBucketType bucketType;
    @XmlAttribute(name = "attribute-id")
    protected String attributeId;
    @XmlAttribute(name = "system")
    protected Boolean system;

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedString }
     * 
     * 
     */
    public List<SharedTypeLocalizedString> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<SharedTypeLocalizedString>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the valueSet property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeRefinementValueSet }
     *     
     */
    public SimpleTypeRefinementValueSet getValueSet() {
        return valueSet;
    }

    /**
     * Sets the value of the valueSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeRefinementValueSet }
     *     
     */
    public void setValueSet(SimpleTypeRefinementValueSet value) {
        this.valueSet = value;
    }

    /**
     * Gets the value of the sortMode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeSortingMode }
     *     
     */
    public SimpleTypeSortingMode getSortMode() {
        return sortMode;
    }

    /**
     * Sets the value of the sortMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeSortingMode }
     *     
     */
    public void setSortMode(SimpleTypeSortingMode value) {
        this.sortMode = value;
    }

    /**
     * Gets the value of the sortDirection property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeSortingDirection }
     *     
     */
    public SimpleTypeSortingDirection getSortDirection() {
        return sortDirection;
    }

    /**
     * Sets the value of the sortDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeSortingDirection }
     *     
     */
    public void setSortDirection(SimpleTypeSortingDirection value) {
        this.sortDirection = value;
    }

    /**
     * Gets the value of the unbucketedValuesMode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeUnbucketedValuesMode }
     *     
     */
    public SimpleTypeUnbucketedValuesMode getUnbucketedValuesMode() {
        return unbucketedValuesMode;
    }

    /**
     * Sets the value of the unbucketedValuesMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeUnbucketedValuesMode }
     *     
     */
    public void setUnbucketedValuesMode(SimpleTypeUnbucketedValuesMode value) {
        this.unbucketedValuesMode = value;
    }

    /**
     * Gets the value of the cutoffThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCutoffThreshold() {
        return cutoffThreshold;
    }

    /**
     * Sets the value of the cutoffThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCutoffThreshold(Integer value) {
        this.cutoffThreshold = value;
    }

    /**
     * Gets the value of the bucketDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeRefinementBuckets }
     *     
     */
    public ComplexTypeRefinementBuckets getBucketDefinitions() {
        return bucketDefinitions;
    }

    /**
     * Sets the value of the bucketDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeRefinementBuckets }
     *     
     */
    public void setBucketDefinitions(ComplexTypeRefinementBuckets value) {
        this.bucketDefinitions = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeRefinementType }
     *     
     */
    public SimpleTypeRefinementType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeRefinementType }
     *     
     */
    public void setType(SimpleTypeRefinementType value) {
        this.type = value;
    }

    /**
     * Gets the value of the bucketType property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeBucketType }
     *     
     */
    public SimpleTypeBucketType getBucketType() {
        return bucketType;
    }

    /**
     * Sets the value of the bucketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeBucketType }
     *     
     */
    public void setBucketType(SimpleTypeBucketType value) {
        this.bucketType = value;
    }

    /**
     * Gets the value of the attributeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeId() {
        return attributeId;
    }

    /**
     * Sets the value of the attributeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeId(String value) {
        this.attributeId = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSystem() {
        if (system == null) {
            return false;
        } else {
            return system;
        }
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSystem(Boolean value) {
        this.system = value;
    }

}
