//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product.ImageGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.ImageGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="variation" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.ImageGroup.VariationAttributeValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Image" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="view-type" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *       &lt;attribute name="variation-value" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.ImageGroup", propOrder = {
    "variation",
    "image"
})
public class ComplexTypeProductImageGroup {

    protected List<ComplexTypeProductImageGroupVariationAttributeValue> variation;
    protected List<ComplexTypeProductImage> image;
    @XmlAttribute(name = "view-type", required = true)
    protected String viewType;
    @XmlAttribute(name = "variation-value")
    protected String variationValue;

    /**
     * Gets the value of the variation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProductImageGroupVariationAttributeValue }
     * 
     * 
     */
    public List<ComplexTypeProductImageGroupVariationAttributeValue> getVariation() {
        if (variation == null) {
            variation = new ArrayList<ComplexTypeProductImageGroupVariationAttributeValue>();
        }
        return this.variation;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProductImage }
     * 
     * 
     */
    public List<ComplexTypeProductImage> getImage() {
        if (image == null) {
            image = new ArrayList<ComplexTypeProductImage>();
        }
        return this.image;
    }

    /**
     * Gets the value of the viewType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewType() {
        return viewType;
    }

    /**
     * Sets the value of the viewType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewType(String value) {
        this.viewType = value;
    }

    /**
     * Gets the value of the variationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariationValue() {
        return variationValue;
    }

    /**
     * Sets the value of the variationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariationValue(String value) {
        this.variationValue = value;
    }

}
