//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.ProductSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.ProductSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="included-products" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.ProductSpecification.ConditionGroups" minOccurs="0"/>
 *         &lt;element name="excluded-products" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.ProductSpecification.ConditionGroups" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.ProductSpecification", propOrder = {
    "includedProducts",
    "excludedProducts"
})
public class ComplexTypeProductSpecification {

    @XmlElement(name = "included-products")
    protected ComplexTypeProductSpecificationConditionGroups includedProducts;
    @XmlElement(name = "excluded-products")
    protected ComplexTypeProductSpecificationConditionGroups excludedProducts;

    /**
     * Gets the value of the includedProducts property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductSpecificationConditionGroups }
     *     
     */
    public ComplexTypeProductSpecificationConditionGroups getIncludedProducts() {
        return includedProducts;
    }

    /**
     * Sets the value of the includedProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductSpecificationConditionGroups }
     *     
     */
    public void setIncludedProducts(ComplexTypeProductSpecificationConditionGroups value) {
        this.includedProducts = value;
    }

    /**
     * Gets the value of the excludedProducts property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductSpecificationConditionGroups }
     *     
     */
    public ComplexTypeProductSpecificationConditionGroups getExcludedProducts() {
        return excludedProducts;
    }

    /**
     * Sets the value of the excludedProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductSpecificationConditionGroups }
     *     
     */
    public void setExcludedProducts(ComplexTypeProductSpecificationConditionGroups value) {
        this.excludedProducts = value;
    }

}
