//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javawithease.javaclass package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Header_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "header");
    private final static QName _Recommendation_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "recommendation");
    private final static QName _Category_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "category");
    private final static QName _CategoryAssignment_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "category-assignment");
    private final static QName _Product_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "product");
    private final static QName _ProductOption_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "product-option");
    private final static QName _VariationAttribute_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "variation-attribute");
    private final static QName _ProductAttributeDefinitions_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "product-attribute-definitions");
    private final static QName _SharedTypeCustomAttributeValue_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "value");
    private final static QName _ComplexTypeCategoryOnlineTo_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "online-to");
    private final static QName _ComplexTypeCategoryOnlineFrom_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "online-from");
    private final static QName _ComplexTypeProductSpecificationRuleLastCalculated_QNAME = new QName("http://www.demandware.com/xml/impex/catalog/2006-10-31", "last-calculated");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javawithease.javaclass
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeDefinition }
     * 
     */
    public ComplexTypeAttributeDefinition createComplexTypeAttributeDefinition() {
        return new ComplexTypeAttributeDefinition();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsVariant }
     * 
     */
    public ComplexTypeProductVariationsVariant createComplexTypeProductVariationsVariant() {
        return new ComplexTypeProductVariationsVariant();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsAttributes }
     * 
     */
    public ComplexTypeProductVariationsAttributes createComplexTypeProductVariationsAttributes() {
        return new ComplexTypeProductVariationsAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeProductClassificationCategory }
     * 
     */
    public ComplexTypeProductClassificationCategory createComplexTypeProductClassificationCategory() {
        return new ComplexTypeProductClassificationCategory();
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeDefinitions }
     * 
     */
    public ComplexTypeAttributeDefinitions createComplexTypeAttributeDefinitions() {
        return new ComplexTypeAttributeDefinitions();
    }

    /**
     * Create an instance of {@link ComplexTypeProductOptionReference }
     * 
     */
    public ComplexTypeProductOptionReference createComplexTypeProductOptionReference() {
        return new ComplexTypeProductOptionReference();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariations }
     * 
     */
    public ComplexTypeProductVariations createComplexTypeProductVariations() {
        return new ComplexTypeProductVariations();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryAssignmentVariationAssignments }
     * 
     */
    public ComplexTypeCategoryAssignmentVariationAssignments createComplexTypeCategoryAssignmentVariationAssignments() {
        return new ComplexTypeCategoryAssignmentVariationAssignments();
    }

    /**
     * Create an instance of {@link ComplexTypeBlockedRefinementDefinition }
     * 
     */
    public ComplexTypeBlockedRefinementDefinition createComplexTypeBlockedRefinementDefinition() {
        return new ComplexTypeBlockedRefinementDefinition();
    }

    /**
     * Create an instance of {@link ComplexTypeRefinementBuckets }
     * 
     */
    public ComplexTypeRefinementBuckets createComplexTypeRefinementBuckets() {
        return new ComplexTypeRefinementBuckets();
    }

    /**
     * Create an instance of {@link ComplexTypeRefinementDefinition }
     * 
     */
    public ComplexTypeRefinementDefinition createComplexTypeRefinementDefinition() {
        return new ComplexTypeRefinementDefinition();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttributes }
     * 
     */
    public SharedTypeCustomAttributes createSharedTypeCustomAttributes() {
        return new SharedTypeCustomAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationProductCategoryFilter }
     * 
     */
    public ComplexTypeProductSpecificationProductCategoryFilter createComplexTypeProductSpecificationProductCategoryFilter() {
        return new ComplexTypeProductSpecificationProductCategoryFilter();
    }

    /**
     * Create an instance of {@link ComplexTypeHeader }
     * 
     */
    public ComplexTypeHeader createComplexTypeHeader() {
        return new ComplexTypeHeader();
    }

    /**
     * Create an instance of {@link ComplexTypeProductCategoryLinks }
     * 
     */
    public ComplexTypeProductCategoryLinks createComplexTypeProductCategoryLinks() {
        return new ComplexTypeProductCategoryLinks();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificDateTime }
     * 
     */
    public SharedTypeSiteSpecificDateTime createSharedTypeSiteSpecificDateTime() {
        return new SharedTypeSiteSpecificDateTime();
    }

    /**
     * Create an instance of {@link ComplexTypeProductProductLink }
     * 
     */
    public ComplexTypeProductProductLink createComplexTypeProductProductLink() {
        return new ComplexTypeProductProductLink();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionValue }
     * 
     */
    public ComplexTypeOptionValue createComplexTypeOptionValue() {
        return new ComplexTypeOptionValue();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryAssignmentVariationAssignment }
     * 
     */
    public ComplexTypeCategoryAssignmentVariationAssignment createComplexTypeCategoryAssignmentVariationAssignment() {
        return new ComplexTypeCategoryAssignmentVariationAssignment();
    }

    /**
     * Create an instance of {@link ComplexTypeProductProductSetProduct }
     * 
     */
    public ComplexTypeProductProductSetProduct createComplexTypeProductProductSetProduct() {
        return new ComplexTypeProductProductSetProduct();
    }

    /**
     * Create an instance of {@link ComplexTypeThresholdRefinementBucket }
     * 
     */
    public ComplexTypeThresholdRefinementBucket createComplexTypeThresholdRefinementBucket() {
        return new ComplexTypeThresholdRefinementBucket();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificInt }
     * 
     */
    public SharedTypeSiteSpecificInt createSharedTypeSiteSpecificInt() {
        return new SharedTypeSiteSpecificInt();
    }

    /**
     * Create an instance of {@link ComplexTypeProductCategoryLink }
     * 
     */
    public ComplexTypeProductCategoryLink createComplexTypeProductCategoryLink() {
        return new ComplexTypeProductCategoryLink();
    }

    /**
     * Create an instance of {@link ComplexTypeValueDefinition }
     * 
     */
    public ComplexTypeValueDefinition createComplexTypeValueDefinition() {
        return new ComplexTypeValueDefinition();
    }

    /**
     * Create an instance of {@link ComplexTypeVariationAttributeValue }
     * 
     */
    public ComplexTypeVariationAttributeValue createComplexTypeVariationAttributeValue() {
        return new ComplexTypeVariationAttributeValue();
    }

    /**
     * Create an instance of {@link ComplexTypeProductImages }
     * 
     */
    public ComplexTypeProductImages createComplexTypeProductImages() {
        return new ComplexTypeProductImages();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link ComplexTypeProductProductSetProducts }
     * 
     */
    public ComplexTypeProductProductSetProducts createComplexTypeProductProductSetProducts() {
        return new ComplexTypeProductProductSetProducts();
    }

    /**
     * Create an instance of {@link ComplexTypeProductImageGroupVariationAttributeValue }
     * 
     */
    public ComplexTypeProductImageGroupVariationAttributeValue createComplexTypeProductImageGroupVariationAttributeValue() {
        return new ComplexTypeProductImageGroupVariationAttributeValue();
    }

    /**
     * Create an instance of {@link SharedTypeLocalizedText }
     * 
     */
    public SharedTypeLocalizedText createSharedTypeLocalizedText() {
        return new SharedTypeLocalizedText();
    }

    /**
     * Create an instance of {@link ComplexTypeProduct }
     * 
     */
    public ComplexTypeProduct createComplexTypeProduct() {
        return new ComplexTypeProduct();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryAssignmentVariationAssignmentValues }
     * 
     */
    public ComplexTypeCategoryAssignmentVariationAssignmentValues createComplexTypeCategoryAssignmentVariationAssignmentValues() {
        return new ComplexTypeCategoryAssignmentVariationAssignmentValues();
    }

    /**
     * Create an instance of {@link ComplexTypeRefinementDefinitions }
     * 
     */
    public ComplexTypeRefinementDefinitions createComplexTypeRefinementDefinitions() {
        return new ComplexTypeRefinementDefinitions();
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeReference }
     * 
     */
    public ComplexTypeAttributeReference createComplexTypeAttributeReference() {
        return new ComplexTypeAttributeReference();
    }

    /**
     * Create an instance of {@link ComplexTypeProductImage }
     * 
     */
    public ComplexTypeProductImage createComplexTypeProductImage() {
        return new ComplexTypeProductImage();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificCustomAttributes }
     * 
     */
    public SharedTypeSiteSpecificCustomAttributes createSharedTypeSiteSpecificCustomAttributes() {
        return new SharedTypeSiteSpecificCustomAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsAttributesAttributeValues }
     * 
     */
    public ComplexTypeProductVariationsAttributesAttributeValues createComplexTypeProductVariationsAttributesAttributeValues() {
        return new ComplexTypeProductVariationsAttributesAttributeValues();
    }

    /**
     * Create an instance of {@link ComplexTypeImageExternalLocation }
     * 
     */
    public ComplexTypeImageExternalLocation createComplexTypeImageExternalLocation() {
        return new ComplexTypeImageExternalLocation();
    }

    /**
     * Create an instance of {@link ComplexTypeImageSettings }
     * 
     */
    public ComplexTypeImageSettings createComplexTypeImageSettings() {
        return new ComplexTypeImageSettings();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationConditionGroup }
     * 
     */
    public ComplexTypeProductSpecificationConditionGroup createComplexTypeProductSpecificationConditionGroup() {
        return new ComplexTypeProductSpecificationConditionGroup();
    }

    /**
     * Create an instance of {@link ComplexTypeVariationAttribute }
     * 
     */
    public ComplexTypeVariationAttribute createComplexTypeVariationAttribute() {
        return new ComplexTypeVariationAttribute();
    }

    /**
     * Create an instance of {@link SharedTypeLocalizedString }
     * 
     */
    public SharedTypeLocalizedString createSharedTypeLocalizedString() {
        return new SharedTypeLocalizedString();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionValuePrice }
     * 
     */
    public ComplexTypeOptionValuePrice createComplexTypeOptionValuePrice() {
        return new ComplexTypeOptionValuePrice();
    }

    /**
     * Create an instance of {@link ComplexTypeProductBundledProduct }
     * 
     */
    public ComplexTypeProductBundledProduct createComplexTypeProductBundledProduct() {
        return new ComplexTypeProductBundledProduct();
    }

    /**
     * Create an instance of {@link ComplexTypeVariationAttributeValues }
     * 
     */
    public ComplexTypeVariationAttributeValues createComplexTypeVariationAttributeValues() {
        return new ComplexTypeVariationAttributeValues();
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeGroups }
     * 
     */
    public ComplexTypeAttributeGroups createComplexTypeAttributeGroups() {
        return new ComplexTypeAttributeGroups();
    }

    /**
     * Create an instance of {@link ComplexTypePriceRefinementBucket }
     * 
     */
    public ComplexTypePriceRefinementBucket createComplexTypePriceRefinementBucket() {
        return new ComplexTypePriceRefinementBucket();
    }

    /**
     * Create an instance of {@link ComplexTypeImageInternalLocation }
     * 
     */
    public ComplexTypeImageInternalLocation createComplexTypeImageInternalLocation() {
        return new ComplexTypeImageInternalLocation();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttribute }
     * 
     */
    public SharedTypeCustomAttribute createSharedTypeCustomAttribute() {
        return new SharedTypeCustomAttribute();
    }

    /**
     * Create an instance of {@link ComplexTypeOption }
     * 
     */
    public ComplexTypeOption createComplexTypeOption() {
        return new ComplexTypeOption();
    }

    /**
     * Create an instance of {@link ComplexTypePageMetaTagRule }
     * 
     */
    public ComplexTypePageMetaTagRule createComplexTypePageMetaTagRule() {
        return new ComplexTypePageMetaTagRule();
    }

    /**
     * Create an instance of {@link ComplexTypeValueDefinitions }
     * 
     */
    public ComplexTypeValueDefinitions createComplexTypeValueDefinitions() {
        return new ComplexTypeValueDefinitions();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryLinks }
     * 
     */
    public ComplexTypeCategoryLinks createComplexTypeCategoryLinks() {
        return new ComplexTypeCategoryLinks();
    }

    /**
     * Create an instance of {@link ComplexTypeImageViewTypes }
     * 
     */
    public ComplexTypeImageViewTypes createComplexTypeImageViewTypes() {
        return new ComplexTypeImageViewTypes();
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeRefinementBucket }
     * 
     */
    public ComplexTypeAttributeRefinementBucket createComplexTypeAttributeRefinementBucket() {
        return new ComplexTypeAttributeRefinementBucket();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationProductIDFilter }
     * 
     */
    public ComplexTypeProductSpecificationProductIDFilter createComplexTypeProductSpecificationProductIDFilter() {
        return new ComplexTypeProductSpecificationProductIDFilter();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionValuePrices }
     * 
     */
    public ComplexTypeOptionValuePrices createComplexTypeOptionValuePrices() {
        return new ComplexTypeOptionValuePrices();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationRule }
     * 
     */
    public ComplexTypeProductSpecificationRule createComplexTypeProductSpecificationRule() {
        return new ComplexTypeProductSpecificationRule();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsAttributesAttributeValue }
     * 
     */
    public ComplexTypeProductVariationsAttributesAttributeValue createComplexTypeProductVariationsAttributesAttributeValue() {
        return new ComplexTypeProductVariationsAttributesAttributeValue();
    }

    /**
     * Create an instance of {@link ComplexTypeProductRetailSetProducts }
     * 
     */
    public ComplexTypeProductRetailSetProducts createComplexTypeProductRetailSetProducts() {
        return new ComplexTypeProductRetailSetProducts();
    }

    /**
     * Create an instance of {@link ComplexTypePageAttributes }
     * 
     */
    public ComplexTypePageAttributes createComplexTypePageAttributes() {
        return new ComplexTypePageAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationProductAttributeFilter }
     * 
     */
    public ComplexTypeProductSpecificationProductAttributeFilter createComplexTypeProductSpecificationProductAttributeFilter() {
        return new ComplexTypeProductSpecificationProductAttributeFilter();
    }

    /**
     * Create an instance of {@link ComplexTypeProductStoreAttributes }
     * 
     */
    public ComplexTypeProductStoreAttributes createComplexTypeProductStoreAttributes() {
        return new ComplexTypeProductStoreAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryAssignment }
     * 
     */
    public ComplexTypeCategoryAssignment createComplexTypeCategoryAssignment() {
        return new ComplexTypeCategoryAssignment();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificSiteMapPriority }
     * 
     */
    public SharedTypeSiteSpecificSiteMapPriority createSharedTypeSiteSpecificSiteMapPriority() {
        return new SharedTypeSiteSpecificSiteMapPriority();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionValues }
     * 
     */
    public ComplexTypeOptionValues createComplexTypeOptionValues() {
        return new ComplexTypeOptionValues();
    }

    /**
     * Create an instance of {@link ComplexTypePageMetaTagRules }
     * 
     */
    public ComplexTypePageMetaTagRules createComplexTypePageMetaTagRules() {
        return new ComplexTypePageMetaTagRules();
    }

    /**
     * Create an instance of {@link ComplexTypeRecommendation }
     * 
     */
    public ComplexTypeRecommendation createComplexTypeRecommendation() {
        return new ComplexTypeRecommendation();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificBoolean }
     * 
     */
    public SharedTypeSiteSpecificBoolean createSharedTypeSiteSpecificBoolean() {
        return new SharedTypeSiteSpecificBoolean();
    }

    /**
     * Create an instance of {@link ComplexTypeProductOptions }
     * 
     */
    public ComplexTypeProductOptions createComplexTypeProductOptions() {
        return new ComplexTypeProductOptions();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationConditionGroups }
     * 
     */
    public ComplexTypeProductSpecificationConditionGroups createComplexTypeProductSpecificationConditionGroups() {
        return new ComplexTypeProductSpecificationConditionGroups();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsAttributesAttribute }
     * 
     */
    public ComplexTypeProductVariationsAttributesAttribute createComplexTypeProductVariationsAttributesAttribute() {
        return new ComplexTypeProductVariationsAttributesAttribute();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificSiteMapChangeFrequency }
     * 
     */
    public SharedTypeSiteSpecificSiteMapChangeFrequency createSharedTypeSiteSpecificSiteMapChangeFrequency() {
        return new SharedTypeSiteSpecificSiteMapChangeFrequency();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecificationProductBrandFilter }
     * 
     */
    public ComplexTypeProductSpecificationProductBrandFilter createComplexTypeProductSpecificationProductBrandFilter() {
        return new ComplexTypeProductSpecificationProductBrandFilter();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsVariants }
     * 
     */
    public ComplexTypeProductVariationsVariants createComplexTypeProductVariationsVariants() {
        return new ComplexTypeProductVariationsVariants();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsVariationGroup }
     * 
     */
    public ComplexTypeProductVariationsVariationGroup createComplexTypeProductVariationsVariationGroup() {
        return new ComplexTypeProductVariationsVariationGroup();
    }

    /**
     * Create an instance of {@link ComplexTypeCategoryLink }
     * 
     */
    public ComplexTypeCategoryLink createComplexTypeCategoryLink() {
        return new ComplexTypeCategoryLink();
    }

    /**
     * Create an instance of {@link SharedTypeSiteSpecificCustomAttribute }
     * 
     */
    public SharedTypeSiteSpecificCustomAttribute createSharedTypeSiteSpecificCustomAttribute() {
        return new SharedTypeSiteSpecificCustomAttribute();
    }

    /**
     * Create an instance of {@link ComplexTypePeriodRefinementBucket }
     * 
     */
    public ComplexTypePeriodRefinementBucket createComplexTypePeriodRefinementBucket() {
        return new ComplexTypePeriodRefinementBucket();
    }

    /**
     * Create an instance of {@link ComplexTypeAttributeGroup }
     * 
     */
    public ComplexTypeAttributeGroup createComplexTypeAttributeGroup() {
        return new ComplexTypeAttributeGroup();
    }

    /**
     * Create an instance of {@link ComplexTypeProductProductLinks }
     * 
     */
    public ComplexTypeProductProductLinks createComplexTypeProductProductLinks() {
        return new ComplexTypeProductProductLinks();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationAttributeReference }
     * 
     */
    public ComplexTypeProductVariationAttributeReference createComplexTypeProductVariationAttributeReference() {
        return new ComplexTypeProductVariationAttributeReference();
    }

    /**
     * Create an instance of {@link ComplexTypeProductRetailSetProduct }
     * 
     */
    public ComplexTypeProductRetailSetProduct createComplexTypeProductRetailSetProduct() {
        return new ComplexTypeProductRetailSetProduct();
    }

    /**
     * Create an instance of {@link ComplexTypeProductSpecification }
     * 
     */
    public ComplexTypeProductSpecification createComplexTypeProductSpecification() {
        return new ComplexTypeProductSpecification();
    }

    /**
     * Create an instance of {@link ComplexTypeProductBundledProducts }
     * 
     */
    public ComplexTypeProductBundledProducts createComplexTypeProductBundledProducts() {
        return new ComplexTypeProductBundledProducts();
    }

    /**
     * Create an instance of {@link ComplexTypeProductVariationsVariationGroups }
     * 
     */
    public ComplexTypeProductVariationsVariationGroups createComplexTypeProductVariationsVariationGroups() {
        return new ComplexTypeProductVariationsVariationGroups();
    }

    /**
     * Create an instance of {@link ComplexTypeCategory }
     * 
     */
    public ComplexTypeCategory createComplexTypeCategory() {
        return new ComplexTypeCategory();
    }

    /**
     * Create an instance of {@link ComplexTypeProductImageGroup }
     * 
     */
    public ComplexTypeProductImageGroup createComplexTypeProductImageGroup() {
        return new ComplexTypeProductImageGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "header")
    public JAXBElement<ComplexTypeHeader> createHeader(ComplexTypeHeader value) {
        return new JAXBElement<ComplexTypeHeader>(_Header_QNAME, ComplexTypeHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeRecommendation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "recommendation")
    public JAXBElement<ComplexTypeRecommendation> createRecommendation(ComplexTypeRecommendation value) {
        return new JAXBElement<ComplexTypeRecommendation>(_Recommendation_QNAME, ComplexTypeRecommendation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "category")
    public JAXBElement<ComplexTypeCategory> createCategory(ComplexTypeCategory value) {
        return new JAXBElement<ComplexTypeCategory>(_Category_QNAME, ComplexTypeCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeCategoryAssignment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "category-assignment")
    public JAXBElement<ComplexTypeCategoryAssignment> createCategoryAssignment(ComplexTypeCategoryAssignment value) {
        return new JAXBElement<ComplexTypeCategoryAssignment>(_CategoryAssignment_QNAME, ComplexTypeCategoryAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "product")
    public JAXBElement<ComplexTypeProduct> createProduct(ComplexTypeProduct value) {
        return new JAXBElement<ComplexTypeProduct>(_Product_QNAME, ComplexTypeProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "product-option")
    public JAXBElement<ComplexTypeOption> createProductOption(ComplexTypeOption value) {
        return new JAXBElement<ComplexTypeOption>(_ProductOption_QNAME, ComplexTypeOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeVariationAttribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "variation-attribute")
    public JAXBElement<ComplexTypeVariationAttribute> createVariationAttribute(ComplexTypeVariationAttribute value) {
        return new JAXBElement<ComplexTypeVariationAttribute>(_VariationAttribute_QNAME, ComplexTypeVariationAttribute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeAttributeDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "product-attribute-definitions")
    public JAXBElement<ComplexTypeAttributeDefinitions> createProductAttributeDefinitions(ComplexTypeAttributeDefinitions value) {
        return new JAXBElement<ComplexTypeAttributeDefinitions>(_ProductAttributeDefinitions_QNAME, ComplexTypeAttributeDefinitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "value", scope = SharedTypeCustomAttribute.class)
    public JAXBElement<String> createSharedTypeCustomAttributeValue(String value) {
        return new JAXBElement<String>(_SharedTypeCustomAttributeValue_QNAME, String.class, SharedTypeCustomAttribute.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "online-to", scope = ComplexTypeCategory.class)
    public JAXBElement<XMLGregorianCalendar> createComplexTypeCategoryOnlineTo(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ComplexTypeCategoryOnlineTo_QNAME, XMLGregorianCalendar.class, ComplexTypeCategory.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "online-from", scope = ComplexTypeCategory.class)
    public JAXBElement<XMLGregorianCalendar> createComplexTypeCategoryOnlineFrom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ComplexTypeCategoryOnlineFrom_QNAME, XMLGregorianCalendar.class, ComplexTypeCategory.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", name = "last-calculated", scope = ComplexTypeProductSpecificationRule.class)
    public JAXBElement<XMLGregorianCalendar> createComplexTypeProductSpecificationRuleLastCalculated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ComplexTypeProductSpecificationRuleLastCalculated_QNAME, XMLGregorianCalendar.class, ComplexTypeProductSpecificationRule.class, value);
    }

}
