//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.datamigration.javaclass;
