//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 12:14:50 pm IST 
//


package com.datamigration.javaclass;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleType.AttributeComparator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="simpleType.AttributeComparator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="less than"/>
 *     &lt;enumeration value="greater than"/>
 *     &lt;enumeration value="equals"/>
 *     &lt;enumeration value="is not equal"/>
 *     &lt;enumeration value="exists"/>
 *     &lt;enumeration value="does not exist"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "simpleType.AttributeComparator")
@XmlEnum
public enum SimpleTypeAttributeComparator {

    @XmlEnumValue("less than")
    LESS_THAN("less than"),
    @XmlEnumValue("greater than")
    GREATER_THAN("greater than"),
    @XmlEnumValue("equals")
    EQUALS("equals"),
    @XmlEnumValue("is not equal")
    IS_NOT_EQUAL("is not equal"),
    @XmlEnumValue("exists")
    EXISTS("exists"),
    @XmlEnumValue("does not exist")
    DOES_NOT_EXIST("does not exist");
    private final String value;

    SimpleTypeAttributeComparator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleTypeAttributeComparator fromValue(String v) {
        for (SimpleTypeAttributeComparator c: SimpleTypeAttributeComparator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
