//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 10:48:34 pm IST 
//


package com.demandware.xml.impex.customergroup._2007_06_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MembershipRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MembershipRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="included-customers" type="{http://www.demandware.com/xml/impex/customergroup/2007-06-30}ConditionGroups"/>
 *         &lt;element name="excluded-customers" type="{http://www.demandware.com/xml/impex/customergroup/2007-06-30}ConditionGroups" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MembershipRule", propOrder = {
    "includedCustomers",
    "excludedCustomers"
})
public class MembershipRule {

    @XmlElement(name = "included-customers", required = true)
    protected ConditionGroups includedCustomers;
    @XmlElement(name = "excluded-customers")
    protected ConditionGroups excludedCustomers;

    /**
     * Gets the value of the includedCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionGroups }
     *     
     */
    public ConditionGroups getIncludedCustomers() {
        return includedCustomers;
    }

    /**
     * Sets the value of the includedCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionGroups }
     *     
     */
    public void setIncludedCustomers(ConditionGroups value) {
        this.includedCustomers = value;
    }

    /**
     * Gets the value of the excludedCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionGroups }
     *     
     */
    public ConditionGroups getExcludedCustomers() {
        return excludedCustomers;
    }

    /**
     * Sets the value of the excludedCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionGroups }
     *     
     */
    public void setExcludedCustomers(ConditionGroups value) {
        this.excludedCustomers = value;
    }

}
