//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 10:48:34 pm IST 
//


package com.demandware.xml.impex.customergroup._2007_06_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demandware.xml.impex.customergroup._2007_06_30 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupAssignment_QNAME = new QName("http://www.demandware.com/xml/impex/customergroup/2007-06-30", "group-assignment");
    private final static QName _CustomerGroup_QNAME = new QName("http://www.demandware.com/xml/impex/customergroup/2007-06-30", "customer-group");
    private final static QName _CustomAttributeValue_QNAME = new QName("http://www.demandware.com/xml/impex/customergroup/2007-06-30", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demandware.xml.impex.customergroup._2007_06_30
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerGroupAssignment }
     * 
     */
    public CustomerGroupAssignment createCustomerGroupAssignment() {
        return new CustomerGroupAssignment();
    }

    /**
     * Create an instance of {@link ConditionGroup }
     * 
     */
    public ConditionGroup createConditionGroup() {
        return new ConditionGroup();
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link NumberRange }
     * 
     */
    public NumberRange createNumberRange() {
        return new NumberRange();
    }

    /**
     * Create an instance of {@link IntRange }
     * 
     */
    public IntRange createIntRange() {
        return new IntRange();
    }

    /**
     * Create an instance of {@link CustomAttributes }
     * 
     */
    public CustomAttributes createCustomAttributes() {
        return new CustomAttributes();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link CustomerGroups }
     * 
     */
    public CustomerGroups createCustomerGroups() {
        return new CustomerGroups();
    }

    /**
     * Create an instance of {@link ConditionGroups }
     * 
     */
    public ConditionGroups createConditionGroups() {
        return new ConditionGroups();
    }

    /**
     * Create an instance of {@link CustomerGroup }
     * 
     */
    public CustomerGroup createCustomerGroup() {
        return new CustomerGroup();
    }

    /**
     * Create an instance of {@link CustomAttribute }
     * 
     */
    public CustomAttribute createCustomAttribute() {
        return new CustomAttribute();
    }

    /**
     * Create an instance of {@link MembershipRule }
     * 
     */
    public MembershipRule createMembershipRule() {
        return new MembershipRule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerGroupAssignment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customergroup/2007-06-30", name = "group-assignment")
    public JAXBElement<CustomerGroupAssignment> createGroupAssignment(CustomerGroupAssignment value) {
        return new JAXBElement<CustomerGroupAssignment>(_GroupAssignment_QNAME, CustomerGroupAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customergroup/2007-06-30", name = "customer-group")
    public JAXBElement<CustomerGroup> createCustomerGroup(CustomerGroup value) {
        return new JAXBElement<CustomerGroup>(_CustomerGroup_QNAME, CustomerGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/customergroup/2007-06-30", name = "value", scope = CustomAttribute.class)
    public JAXBElement<String> createCustomAttributeValue(String value) {
        return new JAXBElement<String>(_CustomAttributeValue_QNAME, String.class, CustomAttribute.class, value);
    }

}
