package com.datamigration.pojo;

import java.util.HashMap;

public class CatgeoryExclusionInclusion {
	private  HashMap<String,String> ksCategoryMap_Inclusion = new HashMap<String,String>();

	private  HashMap<String,String> kssCategoryMap_Inclusion = new HashMap<String,String>();
	private  HashMap<String,String> ksCategoryMap_Exclusion = new HashMap<String,String>();
	private  HashMap<String,String> kssCategoryMap_Exclusion = new HashMap<String,String>();
	public HashMap<String, String> getKsCategoryMap_Inclusion() {
		ksCategoryMap_Inclusion.put("ks-accessories","ks-accessories");
		ksCategoryMap_Inclusion.put("ks-accessories-cosmetic-cases","ks-accessories=>ks-accessories-cosmetic-cases");
		ksCategoryMap_Inclusion.put("ks-accessories-eyewear","ks-accessories=>ks-accessories-eyewear");
		ksCategoryMap_Inclusion.put("ks-accessories-hats-hair-accessories","ks-accessories=>ks-accessories-hats-hair-accessories");
		ksCategoryMap_Inclusion.put("ks-accessories-keychains","ks-accessories=>ks-accessories-keychains");
		ksCategoryMap_Inclusion.put("ks-accessories-legwear","ks-accessories=>ks-accessories-legwear");
		ksCategoryMap_Inclusion.put("ks-accessories-scarves","ks-accessories=>ks-accessories-scarves");
		ksCategoryMap_Inclusion.put("ks-accessories-tech","ks-accessories=>ks-accessories-tech");
		ksCategoryMap_Inclusion.put("ks-accessories-tech-accessories","ks-accessories=>ks-accessories-tech=>ks-accessories-tech-accessories");
		ksCategoryMap_Inclusion.put("ks-accessories-tech-iphone-cases","ks-accessories=>ks-accessories-tech=>ks-accessories-tech-iphone-cases");
		ksCategoryMap_Inclusion.put("ks-accessories-tech-laptop-bags","ks-accessories=>ks-accessories-tech=>ks-accessories-tech-laptop-bags");
		ksCategoryMap_Inclusion.put("ks-accessories-travel-accessories","ks-accessories=>ks-accessories-travel-accessories");
		ksCategoryMap_Inclusion.put("ks-accessories-view-all","ks-accessories=>ks-accessories-view-all");
		ksCategoryMap_Inclusion.put("ks-accessories-watches","ks-accessories=>ks-accessories-watches");
		ksCategoryMap_Inclusion.put("ks-accessories-wearable-tech","ks-accessories=>ks-accessories-wearable-tech");
		ksCategoryMap_Inclusion.put("ks-accesssories-beauty","ks-accessories=>ks-accesssories-beauty");
		ksCategoryMap_Inclusion.put("ks-bedding","ks-home=>ks-bedding");
		ksCategoryMap_Inclusion.put("ks-bedding-duvets","ks-home=>ks-bedding=>ks-bedding-duvets");
		ksCategoryMap_Inclusion.put("ks-bifold-wallets","ks-wallets=>ks-bifold-wallets");
		ksCategoryMap_Inclusion.put("ks-cards-and-gifts","ks-gifts=>ks-gifts-occasions=>ks-cards-and-gifts");
		ksCategoryMap_Inclusion.put("ks-clothing","ks-clothing");
		ksCategoryMap_Inclusion.put("ks-clothing-bottoms","ks-clothing=>ks-clothing-bottoms");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits","ks-clothing=>ks-clothing-dresses-jumpsuits");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits-day","ks-clothing=>ks-clothing-dresses-jumpsuits=>ks-clothing-dresses-jumpsuits-day");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits-evening","ks-clothing=>ks-clothing-dresses-jumpsuits=>ks-clothing-dresses-jumpsuits-evening");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits-midi","ks-clothing=>ks-clothing-dresses-jumpsuits=>ks-clothing-dresses-jumpsuits-midi");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits-mini","ks-clothing=>ks-clothing-dresses-jumpsuits=>ks-clothing-dresses-jumpsuits-mini");
		ksCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits-wear-to-work","ks-clothing=>ks-clothing-dresses-jumpsuits=>ks-clothing-dresses-jumpsuits-wear-to-work");
		ksCategoryMap_Inclusion.put("ks-clothing-matching-sets","ks-clothing=>ks-clothing-matching-sets");
		ksCategoryMap_Inclusion.put("ks-dresses-bridal","ks-clothing=>ks-clothing-shops=>ks-clothing-shops-the-bridal-shop");
		ksCategoryMap_Inclusion.put("ks-clothing-sleepwear","ks-clothing=>ks-clothing-sleepwear");
		ksCategoryMap_Inclusion.put("ks-clothing-swimwear","ks-clothing=>ks-clothing-swimwear");
		ksCategoryMap_Inclusion.put("ks-clothing-tops","ks-clothing=>ks-clothing-tops");
		ksCategoryMap_Inclusion.put("ks-clothing-view-all","ks-clothing=>ks-clothing-view-all");
		ksCategoryMap_Inclusion.put("ks-coffee-and-tea","ks-home=>ks-home-kitchenware=>ks-coffee-and-tea");
		ksCategoryMap_Inclusion.put("ks-coin-purses-keychain wallets","ks-wallets=>ks-coin-purses-keychain wallets");
		ksCategoryMap_Inclusion.put("ks-decorative-pillows","ks-home=>ks-home-accents-and-decor=>ks-decorative-pillows");
		ksCategoryMap_Inclusion.put("ks-gift-cards","ks-gifts=>ks-gift-cards");
		ksCategoryMap_Inclusion.put("ks-gift-guide-100-and-under","ks-gifts=>ks-gift-guide-100-and-under");
		ksCategoryMap_Inclusion.put("ks-gift-guide-200-and-under","ks-gifts=>ks-gift-guide-200-and-under");
		ksCategoryMap_Inclusion.put("ks-gift-guide-50-and-under","ks-gifts=>ks-gift-guide-50-and-under");
		ksCategoryMap_Inclusion.put("ks-gift-guide-for-him","ks-gifts=>ks-gifts-occasions=>ks-gift-guide-for-him");
		ksCategoryMap_Inclusion.put("ks-gifts","ks-gifts");
		ksCategoryMap_Inclusion.put("ks-gifts-anniversary","ks-gifts=>ks-gifts-occasions=>ks-gifts-anniversary");
		ksCategoryMap_Inclusion.put("ks-gifts-best-sellers","ks-gifts=>ks-gifts-best-sellers");
		ksCategoryMap_Inclusion.put("ks-gifts-birthday","ks-gifts=>ks-gifts-occasions=>ks-gifts-birthday");
		ksCategoryMap_Inclusion.put("ks-gift-services","ks-gifts=>ks-gift-services");
		ksCategoryMap_Inclusion.put("ks-gifts-housewarming","ks-gifts=>ks-gifts-occasions=>ks-gifts-housewarming");
		ksCategoryMap_Inclusion.put("ks-gifts-little-indulgences","ks-gifts=>ks-gifts-little-indulgences");
		ksCategoryMap_Inclusion.put("ks-gifts-luxury","ks-gifts=>ks-gifts-luxury");
		ksCategoryMap_Inclusion.put("ks-gifts-view-all","ks-gifts=>ks-gifts-view-all");
		ksCategoryMap_Inclusion.put("ks-handbags","ks-handbags");
		ksCategoryMap_Inclusion.put("ks-all-day-tote","ks-handbags=>ks-handbags-collections=>ks-handbags-all-day-tote");
		ksCategoryMap_Inclusion.put("ks-travel-bags","ks-handbags=>ks-handbags-backpacks");
		ksCategoryMap_Inclusion.put("ks-handbags-camera-bags","ks-handbags=>ks-handbags-cross-body=>ks-handbags-camera-bags");
		ksCategoryMap_Inclusion.put("ks-handbags-classic-shop","ks-handbags=>ks-handbags-shops=>ks-handbags-classic-shop");
		ksCategoryMap_Inclusion.put("ks-handbags-cross-body","ks-handbags=>ks-handbags-cross-body");
		ksCategoryMap_Inclusion.put("ks-knott-shop","ks-handbags=>ks-handbags-collections=>ks-handbags-knott-shop");
		ksCategoryMap_Inclusion.put("ks-matching-handbags-and-wallets","ks-handbags=>ks-handbags-shops=>ks-handbags-matching-handbags-and-wallets");
		ksCategoryMap_Inclusion.put("ks-handbags-new-essentials","ks-handbags=>ks-handbags-shops=>ks-handbags-new-essentials");
		ksCategoryMap_Inclusion.put("ks-handbags-new-nylon","ks-handbags=>ks-handbags-shops=>ks-handbags-new-nylon");
		ksCategoryMap_Inclusion.put("ks-handbags-personalization","ks-handbags=>ks-handbags-shops=>ks-handbags-personalization");
		ksCategoryMap_Inclusion.put("ks-handbags-phone-crossbody-bags","ks-handbags=>ks-handbags-cross-body=>ks-handbags-phone-crossbody-bags");
		ksCategoryMap_Inclusion.put("ks-handbags-phone-crossbody-bags-TECH","ks-accessories=>ks-accessories-tech=>ks-handbags-phone-crossbody-bags-TECH");
		ksCategoryMap_Inclusion.put("ks-handbags-satchels","ks-handbags=>ks-handbags-satchels");
		ksCategoryMap_Inclusion.put("ks-handbags-shoulder-bags","ks-handbags=>ks-handbags-shoulder-bags");
		ksCategoryMap_Inclusion.put("ks-handbags-new-logo","ks-handbags=>ks-handbags-collections=>ks-handbags-the-spade-flower-shop");
		ksCategoryMap_Inclusion.put("ks-handbags-totes","ks-handbags=>ks-handbags-totes");
		ksCategoryMap_Inclusion.put("ks-handbags-work-totes","ks-handbags=>ks-handbags-work-totes");
		ksCategoryMap_Inclusion.put("ks-holiday-dressing-shop","ks-new-arrivals=>ks-new-arrivals-shops=>ks-holiday-dressing-shop");
		ksCategoryMap_Inclusion.put("ks-home","ks-home");
		ksCategoryMap_Inclusion.put("ks-home-accents-and-decor","ks-home=>ks-home-accents-and-decor");
		ksCategoryMap_Inclusion.put("ks-home-accents-and-decor-view-all","ks-home=>ks-home-accents-and-decor=>ks-home-accents-and-decor-view-all");
		ksCategoryMap_Inclusion.put("ks-home-agendas-and-journals","ks-home=>ks-home-office-accessories=>ks-home-agendas-and-journals");
		ksCategoryMap_Inclusion.put("ks-home-ceiling-lighting","ks-home=>ks-home-lighting=>ks-home-ceiling-lighting");
		ksCategoryMap_Inclusion.put("ks-home-cocktail-and-bar","ks-home=>ks-home-kitchenware=>ks-home-cocktail-and-bar");
		ksCategoryMap_Inclusion.put("ks-home-desk-accessories","ks-home=>ks-home-office-accessories=>ks-home-desk-accessories");
		ksCategoryMap_Inclusion.put("ks-home-dinnerware-and-flatwware","ks-home=>ks-home-kitchenware=>ks-home-dinnerware-and-flatware");
		ksCategoryMap_Inclusion.put("ks-home-frames","ks-home=>ks-home-accents-and-decor=>ks-home-frames");
		ksCategoryMap_Inclusion.put("ks-home-hosting-supplies","ks-home=>ks-home-shops=>ks-home-hosting-supplies");
		ksCategoryMap_Inclusion.put("ks-home-id-holder","ks-home=>ks-home-office-accessories=>ks-home-id-holder");
		ksCategoryMap_Inclusion.put("ks-home-jewelry-holders","ks-home=>ks-home-accents-and-decor=>ks-home-jewelry-holders");
		ksCategoryMap_Inclusion.put("ks-home-kitchenware","ks-home=>ks-home-kitchenware");
		ksCategoryMap_Inclusion.put("ks-home-kitchenware-view-all","ks-home=>ks-home-kitchenware=>ks-home-kitchenware-view-all");
		ksCategoryMap_Inclusion.put("ks-home-lighting","ks-home=>ks-home-lighting");
		ksCategoryMap_Inclusion.put("ks-home-paperless-post","ks-home=>ks-home-collections=>ks-home-paperless-post");
		ksCategoryMap_Inclusion.put("ks-home-serveware","ks-home=>ks-home-lighting=>ks-home-serveware");
		ksCategoryMap_Inclusion.put("ks-home-table-lamps","ks-home=>ks-home-lighting=>ks-home-table-lamps");
		ksCategoryMap_Inclusion.put("ks-home-urban-stems","ks-home=>ks-home-collections=>ks-home-urban-stems");
		ksCategoryMap_Inclusion.put("ks-home-view-all","ks-home=>ks-home-view-all");
		ksCategoryMap_Inclusion.put("ks-home-wall-lighting","ks-home=>ks-home-lighting=>ks-home-wall-lighting");
		ksCategoryMap_Inclusion.put("ks-jewelry","ks-jewelry");
		ksCategoryMap_Inclusion.put("ks-jewelry-bracelets","ks-jewelry=>ks-jewelry-bracelets");
		ksCategoryMap_Inclusion.put("ks-jewelry-bridal","ks-jewelry=>ks-jewelry-shops=>ks-jewelry-bridal");
		ksCategoryMap_Inclusion.put("ks-jewelry-dangle","ks-jewelry=>ks-jewelry-earrings=>ks-jewelry-dangle");
		ksCategoryMap_Inclusion.put("ks-jewelry-earrings","ks-jewelry=>ks-jewelry-earrings");
		ksCategoryMap_Inclusion.put("ks-jewelry-necklaces","ks-jewelry=>ks-jewelry-necklaces");
		ksCategoryMap_Inclusion.put("ks-personalized-jewelry","ks-jewelry=>ks-jewelry-shops=>ks-jewelry-personalization");
		ksCategoryMap_Inclusion.put("ks-jewelry-rings","ks-jewelry=>ks-jewelry-rings");
		ksCategoryMap_Inclusion.put("ks-jewelry-studs","ks-jewelry=>ks-jewelry-earrings=>ks-jewelry-studs");
		ksCategoryMap_Inclusion.put("ks-jewelry-view-all","ks-jewelry=>ks-jewelry-view-all");
		ksCategoryMap_Inclusion.put("ks-jewelry-watches","ks-jewelry=>ks-jewelry-watches");
		ksCategoryMap_Inclusion.put("ks-jewlery-hoops","ks-jewelry=>ks-jewelry-earrings=>ks-jewlery-hoops");
		ksCategoryMap_Inclusion.put("ks-keds-shoes","ks-shoes=>ks-shoes-collection=>ks-keds-shoes");
		ksCategoryMap_Inclusion.put("ks-kitchen-accessories","ks-home=>ks-home-kitchenware=>ks-kitchen-accessories");
		ksCategoryMap_Inclusion.put("ks-kitchen-organization-and-storage","ks-home=>ks-home-kitchenware=>ks-kitchen-organization-and-storage");
		ksCategoryMap_Inclusion.put("ks-new-arrivals","ks-new-arrivals");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-accessories","ks-new-arrivals=>ks-new-arrivals-accessories");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-clothing","ks-new-arrivals=>ks-new-arrivals-clothing");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-handbags","ks-new-arrivals=>ks-new-arrivals-handbags");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-home-stationery","ks-new-arrivals=>ks-new-arrivals-home-stationery");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-jewelry","ks-new-arrivals=>ks-new-arrivals-jewelry");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-shoes","ks-new-arrivals=>ks-new-arrivals-shoes");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-view-all","ks-new-arrivals=>ks-new-arrivals-view-all");
		ksCategoryMap_Inclusion.put("ks-new-arrivals-wallets","ks-new-arrivals=>ks-new-arrivals-wallets");
		ksCategoryMap_Inclusion.put("ks-new-nylon","ks-new-arrivals=>ks-new-arrivals-shops=>ks-new-nylon");
		ksCategoryMap_Inclusion.put("ks-pillows","ks-home=>ks-bedding=>ks-pillows");
		ksCategoryMap_Inclusion.put("ks-shoes","ks-shoes");
		ksCategoryMap_Inclusion.put("ks-shoes-boots","ks-shoes=>ks-shoes-boots-booties");
		ksCategoryMap_Inclusion.put("ks-shoes-flats","ks-shoes=>ks-shoes-flats");
		ksCategoryMap_Inclusion.put("ks-shoes-heels","ks-shoes=>ks-shoes-heels");
		ksCategoryMap_Inclusion.put("ks-shoes-kids","ks-shoes=>ks-shoes-kids");
		ksCategoryMap_Inclusion.put("ks-shoes-sandals","ks-shoes=>ks-shoes-sandals");
		ksCategoryMap_Inclusion.put("ks-shoes-slippers","ks-shoes=>ks-shoes-slippers");
		ksCategoryMap_Inclusion.put("ks-shoes-sneakers","ks-shoes=>ks-shoes-sneakers");
		ksCategoryMap_Inclusion.put("ks-shoes-view-all","ks-shoes=>ks-shoes-view-all");
		ksCategoryMap_Inclusion.put("ks-wallets","ks-wallets");
		ksCategoryMap_Inclusion.put("ks-wallets-card-holders","ks-wallets=>ks-wallets-card-holders");
		ksCategoryMap_Inclusion.put("ks-wallets-crossbody","ks-wallets=>ks-wallets-crossbody");
		ksCategoryMap_Inclusion.put("ks-wallets-large-wallets","ks-wallets=>ks-wallets-large-wallets");
		ksCategoryMap_Inclusion.put("ks-wallets-cosmetic-cases","ks-wallets=>ks-wallets-makeup-bags-cosmetic-cases");
		ksCategoryMap_Inclusion.put("ks-handbags-matching-handbags-and-wallets","ks-wallets=>ks-wallets-shops=>ks-wallets-matching-handbags-and-wallets");
		ksCategoryMap_Inclusion.put("ks-wallets-view-all","ks-wallets=>ks-wallets-view-all");
		ksCategoryMap_Inclusion.put("ks-wallets-wristlets-pouches","ks-wallets=>ks-wallets-wristlets-pouches");
		return ksCategoryMap_Inclusion;
	}

	public HashMap<String, String> getKssCategoryMap_Inclusion() {
		kssCategoryMap_Inclusion.put("ks-accessories","kss-accessories");
		kssCategoryMap_Inclusion.put("ks-accessories-cold-weather","kss-accessories=>kss-accessories-cold-weather");
		kssCategoryMap_Inclusion.put("ks-accessories-keychains","kss-accessories=>kss-accessories-keychains");
		kssCategoryMap_Inclusion.put("ks-accessories-makeup-bags","kss-accessories=>kss-accessories-makeup-bags");
		kssCategoryMap_Inclusion.put("ks-accessories-scarves","kss-accessories=>kss-accessories-scarves");
		kssCategoryMap_Inclusion.put("ks-accessories-sunglasses","kss-accessories=>kss-accessories-sunglasses");
		kssCategoryMap_Inclusion.put("ks-accessories-tech","kss-accessories=>kss-accessories-tech");
		kssCategoryMap_Inclusion.put("ks-accessories-view-all","kss-accessories=>kss-accessories-view-all");
		kssCategoryMap_Inclusion.put("ks-bundles","kss-bundles");
		kssCategoryMap_Inclusion.put("ks-clothing-all","kss-clothing-all");
		kssCategoryMap_Inclusion.put("ks-clothing-dresses-jumpsuits","kss-clothing-all=>kss-clothing-dresses-jumpsuits");
		kssCategoryMap_Inclusion.put("ks-clothing-jackets-coats","kss-clothing-all=>kss-clothing-jackets-coats");
		kssCategoryMap_Inclusion.put("ks-clothing-lounge","kss-clothing-all=>kss-clothing-lounge");
		kssCategoryMap_Inclusion.put("ks-clothing-pajamas","kss-clothing-all=>kss-clothing-pajamas");
		kssCategoryMap_Inclusion.put("ks-clothing-sweaters","kss-clothing-all=>kss-clothing-sweaters");
		kssCategoryMap_Inclusion.put("ks-clothing-tops-blouses","kss-clothing-all=>kss-clothing-tops-blouses");
		kssCategoryMap_Inclusion.put("ks-clothing-view-all","kss-clothing-all=>kss-clothing-view-all");
		kssCategoryMap_Inclusion.put("ks-daily-deals","kss-daily-deals");
		kssCategoryMap_Inclusion.put("ks-gifts","kss-gifts");
		kssCategoryMap_Inclusion.put("ks-handbags","kss-handbags");
		kssCategoryMap_Inclusion.put("ks-handbags-backpacks-travel-bags","kss-handbags=>kss-handbags-backpackss-travel-bags");
		kssCategoryMap_Inclusion.put("ks-handbags-bucket-bags","kss-handbags=>kss-handbags-bucket-bags");
		kssCategoryMap_Inclusion.put("ks-handbags-crossbodies","kss-handbags=>kss-handbags-crossbodies");
		kssCategoryMap_Inclusion.put("ks-handbags-diaper-bags","kss-handbags=>kss-handbags-diaper-bags");
		kssCategoryMap_Inclusion.put("ks-handbags-laptop-bags","kss-handbags=>kss-handbags-laptop-bags");
		kssCategoryMap_Inclusion.put("ks-handbags-satchels","kss-handbags=>kss-handbags-satchels");
		kssCategoryMap_Inclusion.put("ks-handbags-shoulder-bags","kss-handbags=>kss-handbags-shoulder-bags");
		kssCategoryMap_Inclusion.put("ks-handbags-view-all","kss-handbags=>kss-handbags-view-all");
		kssCategoryMap_Inclusion.put("ks-jewelry","kss-jewelry");
		kssCategoryMap_Inclusion.put("ks-jewelry-bracelets","kss-jewelry=>kss-jewelry-bracelets");
		kssCategoryMap_Inclusion.put("ks-jewelry-earrings","kss-jewelry=>kss-jewelry-earrings");
		kssCategoryMap_Inclusion.put("ks-jewelry-necklaces","kss-jewelry=>kss-jewelry-necklaces");
		kssCategoryMap_Inclusion.put("ks-jewelry-rings","kss-jewelry=>kss-jewelry-rings");
		kssCategoryMap_Inclusion.put("ks-jewelry-view-all","kss-jewelry=>kss-jewelry-view-all");
		kssCategoryMap_Inclusion.put("ks-jewelry-watches","kss-jewelry=>kss-jewelry-watches");
		kssCategoryMap_Inclusion.put("ks-new-arrivals","kss-new-arrivals");
		kssCategoryMap_Inclusion.put("kss-clearance","kss-daily-deals=>kss-clearance");
		kssCategoryMap_Inclusion.put("kss-deal-of-the-day","kss-daily-deals=>kss-deal-of-the-day");
		kssCategoryMap_Inclusion.put("kss-gift-guide-shipping-guidelines","kss-gifts=>kss-gift-guide-shipping-guidelines");
		kssCategoryMap_Inclusion.put("kss-gifts-boxed-sets","kss-gifts=>kss-gifts-boxed-sets");
		kssCategoryMap_Inclusion.put("kss-gift-services","kss-gifts=>kss-gift-services");
		kssCategoryMap_Inclusion.put("kss-gifts-for-grads","kss-gifts=>kss-gifts-for-grads");
		kssCategoryMap_Inclusion.put("kss-gifts-jewelry-gifts","kss-gifts=>kss-gifts-jewelry-gifts");
		kssCategoryMap_Inclusion.put("kss-gifts-lp","kss-gifts=>kss-gifts-lp");
		kssCategoryMap_Inclusion.put("kss-gifts-perfect-pairs","kss-gifts=>kss-gifts-perfect-pairs");
		kssCategoryMap_Inclusion.put("kss-gifts-top-picks","kss-gifts=>kss-gifts-top-picks");
		kssCategoryMap_Inclusion.put("kss-gifts-under-100","kss-gifts=>kss-gifts-under-100");
		kssCategoryMap_Inclusion.put("kss-gifts-under-25","kss-gifts=>kss-gifts-under-25");
		kssCategoryMap_Inclusion.put("kss-gifts-under-50","kss-gifts=>kss-gifts-under-50");
		kssCategoryMap_Inclusion.put("kss-gifts-valentines-day","kss-gifts=>kss-gifts-valentines-day");
		kssCategoryMap_Inclusion.put("kss-gifts-view-all","kss-gifts=>kss-gifts-view-all");
		kssCategoryMap_Inclusion.put("kss-outlet","kss-outlet");
		kssCategoryMap_Inclusion.put("kss-outlet-accessories","kss-outlet=>kss-outlet-accessories");
		kssCategoryMap_Inclusion.put("kss-outlet-bopis","kss-outlet=>kss-outlet-bopis");
		kssCategoryMap_Inclusion.put("kss-outlet-clothing","kss-outlet=>kss-outlet-clothing");
		kssCategoryMap_Inclusion.put("kss-outlet-handbags","kss-outlet=>kss-outlet-handbags");
		kssCategoryMap_Inclusion.put("kss-outlet-jewelry","kss-outlet=>kss-outlet-jewelry");
		kssCategoryMap_Inclusion.put("kss-outlet-locator","kss-outlet=>kss-outlet-locator");
		kssCategoryMap_Inclusion.put("kss-outlet-shoes","kss-outlet=>kss-outlet-shoes");
		kssCategoryMap_Inclusion.put("kss-outlet-view-all","kss-outlet=>kss-outlet-view-all");
		kssCategoryMap_Inclusion.put("kss-outlet-wallets","kss-outlet=>kss-outlet-wallets");
		kssCategoryMap_Inclusion.put("ks-view-all","kss-view-all");
		kssCategoryMap_Inclusion.put("ks-wallets-wristlet-pouches","kss-wallets-wristlet-pouches");
		kssCategoryMap_Inclusion.put("ks-wallets-wristlets-cardholders","kss-wallets-wristlet-pouches=>kss-wallets-wristlets-cardholders");
		kssCategoryMap_Inclusion.put("ks-wallets-wristlets-large-wallets","kss-wallets-wristlet-pouches=>kss-wallets-wristlets-large-wallets");
		kssCategoryMap_Inclusion.put("ks-wallets-wristlets-view-all","kss-wallets-wristlet-pouches=>kss-wallets-wristlets-view-all");
		return kssCategoryMap_Inclusion;
	}

	public HashMap<String, String> getKsCategoryMap_Exclusion() {
		ksCategoryMap_Exclusion.put("ks-best-sellers","ks-handbags>>ks-best-sellers");
		ksCategoryMap_Exclusion.put("ks-bridal","ks-gifts>>ks-bridal");
		ksCategoryMap_Exclusion.put("ks-classic-shop","ks-new-arrivals>>ks-classic-shop");
		ksCategoryMap_Exclusion.put("ks-home-office-accessories-view-all","ks-home>>ks-home-office-accessories>>ks-home-office-accessories-view-all");
		ksCategoryMap_Exclusion.put("ks-i-love-ny","ks-new-arrivals>>ks-i-love-ny");
		ksCategoryMap_Exclusion.put("ks-new-essentials","ks-new-arrivals>>ks-new-essentials");
		ksCategoryMap_Exclusion.put("ks-new-logo","ks-new-arrivals>>ks-new-logo");
		ksCategoryMap_Exclusion.put("ks-new-novelty","ks-new-arrivals>>ks-new-novelty");
		ksCategoryMap_Exclusion.put("ks-personalization","ks-new-arrivals>>ks-personalization");
		ksCategoryMap_Exclusion.put("ks-spencer-shop","ks-handbags>>ks-spencer-shop");
		return ksCategoryMap_Exclusion;
	}

	public HashMap<String, String> getKssCategoryMap_Exclusion() {
		kssCategoryMap_Exclusion.put("fall-essentials","kss-hidden-view-all>>fall-essentials");
		kssCategoryMap_Exclusion.put("ks-back-to-school-shop","kss-hidden-view-all>>ks-back-to-school-shop");
		kssCategoryMap_Exclusion.put("ks-shoes-view-all","ks-shoes-all>>ks-shoes-view-all");
		kssCategoryMap_Exclusion.put("ks-shops-summer-must-haves","kss-hidden-view-all>>shops>>ks-shops-summer-must-haves");
		kssCategoryMap_Exclusion.put("ks-wallets-wristlets-small-wallets","ks-wallets-wristlets>>ks-wallets-wristlets-small-wallets");
		kssCategoryMap_Exclusion.put("kss-backtowork","ks-daily-deals>>kss-deals-hidden>>kss-backtowork");
		kssCategoryMap_Exclusion.put("kss-black-friday-deals","ks-daily-deals>>kss-deals-hidden>>kss-black-friday-deals");
		kssCategoryMap_Exclusion.put("kss-cyber-monday-deals","ks-daily-deals>>kss-deals-hidden>>kss-cyber-monday-deals");
		kssCategoryMap_Exclusion.put("kss-essentials","ks-daily-deals>>kss-deals-hidden>>kss-essentials");
		kssCategoryMap_Exclusion.put("kss-gift-cards","ks-gifts>>kss-gift-cards");
		kssCategoryMap_Exclusion.put("kss-minnie","kss-hidden-view-all>>kss-minnie");
		kssCategoryMap_Exclusion.put("kss-novelty","ks-daily-deals>>kss-deals-hidden>>kss-novelty");
		kssCategoryMap_Exclusion.put("kss-rainbow-shop","ks-daily-deals>>kss-deals-hidden>>kss-rainbow-shop");
		kssCategoryMap_Exclusion.put("kss-sweepstakes-terms","ks-daily-deals>>kss-deals-hidden>>kss-sweepstakes-terms");
		kssCategoryMap_Exclusion.put("kss-travel-shop","kss-hidden-view-all>>kss-travel-shop");
		kssCategoryMap_Exclusion.put("ks-best-sellers","ks-handbags>>ks-best-sellers");
		kssCategoryMap_Exclusion.put("ks-bridal","ks-gifts>>ks-bridal");
		kssCategoryMap_Exclusion.put("ks-classic-shop","ks-new-arrivals>>ks-classic-shop");
		kssCategoryMap_Exclusion.put("ks-home-office-accessories-view-all","ks-home>>ks-home-office-accessories>>ks-home-office-accessories-view-all");
		kssCategoryMap_Exclusion.put("ks-new-logo","ks-new-arrivals>>ks-new-logo");
		kssCategoryMap_Exclusion.put("ks-new-novelty","ks-new-arrivals>>ks-new-novelty");
		kssCategoryMap_Exclusion.put("ks-personalization","ks-new-arrivals>>ks-personalization");
		kssCategoryMap_Exclusion.put("ks-spencer-shop","ks-handbags>>ks-spencer-shop");
		return kssCategoryMap_Exclusion;
	}

	

	
	
}
