//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.04 at 09:29:38 am IST 
//


package com.demandware.xml.impex.productlist._2009_10_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="owner" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Owner" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}simpleType.ProductList.Type"/>
 *         &lt;element name="name" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="registrants" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Registrants" minOccurs="0"/>
 *         &lt;element name="event" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Event" minOccurs="0"/>
 *         &lt;element name="shipping-address" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Address" minOccurs="0"/>
 *         &lt;element name="post-event-shipping-address" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Address" minOccurs="0"/>
 *         &lt;element name="items" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}Items" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="list-id" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}simpleType.Generic.NonEmptyUUID.26" />
 *       &lt;attribute name="mode" type="{http://www.demandware.com/xml/impex/productlist/2009-10-28}simpleType.ImportMode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductList", propOrder = {
    "owner",
    "type",
    "name",
    "description",
    "_public",
    "registrants",
    "event",
    "shippingAddress",
    "postEventShippingAddress",
    "items",
    "customAttributes"
})
public class ProductList {

    protected Owner owner;
    @XmlElement(required = true)
    protected SimpleTypeProductListType type;
    protected String name;
    protected String description;
    @XmlElement(name = "public")
    protected boolean _public;
    protected Registrants registrants;
    protected Event event;
    @XmlElement(name = "shipping-address")
    protected Address shippingAddress;
    @XmlElement(name = "post-event-shipping-address")
    protected Address postEventShippingAddress;
    protected Items items;
    @XmlElement(name = "custom-attributes")
    protected CustomAttributes customAttributes;
    @XmlAttribute(name = "list-id")
    protected String listId;
    @XmlAttribute(name = "mode")
    protected SimpleTypeImportMode mode;

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Owner }
     *     
     */
    public Owner getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Owner }
     *     
     */
    public void setOwner(Owner value) {
        this.owner = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeProductListType }
     *     
     */
    public SimpleTypeProductListType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeProductListType }
     *     
     */
    public void setType(SimpleTypeProductListType value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the public property.
     * 
     */
    public boolean isPublic() {
        return _public;
    }

    /**
     * Sets the value of the public property.
     * 
     */
    public void setPublic(boolean value) {
        this._public = value;
    }

    /**
     * Gets the value of the registrants property.
     * 
     * @return
     *     possible object is
     *     {@link Registrants }
     *     
     */
    public Registrants getRegistrants() {
        return registrants;
    }

    /**
     * Sets the value of the registrants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Registrants }
     *     
     */
    public void setRegistrants(Registrants value) {
        this.registrants = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setShippingAddress(Address value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the postEventShippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPostEventShippingAddress() {
        return postEventShippingAddress;
    }

    /**
     * Sets the value of the postEventShippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPostEventShippingAddress(Address value) {
        this.postEventShippingAddress = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Items }
     *     
     */
    public Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Items }
     *     
     */
    public void setItems(Items value) {
        this.items = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomAttributes }
     *     
     */
    public CustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAttributes }
     *     
     */
    public void setCustomAttributes(CustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the listId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListId() {
        return listId;
    }

    /**
     * Sets the value of the listId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListId(String value) {
        this.listId = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public SimpleTypeImportMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public void setMode(SimpleTypeImportMode value) {
        this.mode = value;
    }

}
