//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.04 at 09:29:38 am IST 
//


package com.demandware.xml.impex.productlist._2009_10_28;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleType.Registrant.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="simpleType.Registrant.Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="registrant"/>
 *     &lt;enumeration value="co-registrant"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "simpleType.Registrant.Type")
@XmlEnum
public enum SimpleTypeRegistrantType {

    @XmlEnumValue("registrant")
    REGISTRANT("registrant"),
    @XmlEnumValue("co-registrant")
    CO_REGISTRANT("co-registrant");
    private final String value;

    SimpleTypeRegistrantType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleTypeRegistrantType fromValue(String v) {
        for (SimpleTypeRegistrantType c: SimpleTypeRegistrantType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
