//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 03:38:01 pm IST 
//


package com.demandware.xml.impex.inventory._2007_05_31;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demandware.xml.impex.inventory._2007_05_31 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Header_QNAME = new QName("http://www.demandware.com/xml/impex/inventory/2007-05-31", "header");
    private final static QName _Record_QNAME = new QName("http://www.demandware.com/xml/impex/inventory/2007-05-31", "record");
    private final static QName _SharedTypeCustomAttributeValue_QNAME = new QName("http://www.demandware.com/xml/impex/inventory/2007-05-31", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demandware.xml.impex.inventory._2007_05_31
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Inventory }
     * 
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link ComplexTypeInventoryRecords }
     * 
     */
    public ComplexTypeInventoryRecords createComplexTypeInventoryRecords() {
        return new ComplexTypeInventoryRecords();
    }

    /**
     * Create an instance of {@link ComplexTypeInventoryRecord }
     * 
     */
    public ComplexTypeInventoryRecord createComplexTypeInventoryRecord() {
        return new ComplexTypeInventoryRecord();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttribute }
     * 
     */
    public SharedTypeCustomAttribute createSharedTypeCustomAttribute() {
        return new SharedTypeCustomAttribute();
    }

    /**
     * Create an instance of {@link ComplexTypeHeader }
     * 
     */
    public ComplexTypeHeader createComplexTypeHeader() {
        return new ComplexTypeHeader();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttributes }
     * 
     */
    public SharedTypeCustomAttributes createSharedTypeCustomAttributes() {
        return new SharedTypeCustomAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypeInventoryList }
     * 
     */
    public ComplexTypeInventoryList createComplexTypeInventoryList() {
        return new ComplexTypeInventoryList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", name = "header")
    public JAXBElement<ComplexTypeHeader> createHeader(ComplexTypeHeader value) {
        return new JAXBElement<ComplexTypeHeader>(_Header_QNAME, ComplexTypeHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeInventoryRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", name = "record")
    public JAXBElement<ComplexTypeInventoryRecord> createRecord(ComplexTypeInventoryRecord value) {
        return new JAXBElement<ComplexTypeInventoryRecord>(_Record_QNAME, ComplexTypeInventoryRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", name = "value", scope = SharedTypeCustomAttribute.class)
    public JAXBElement<String> createSharedTypeCustomAttributeValue(String value) {
        return new JAXBElement<String>(_SharedTypeCustomAttributeValue_QNAME, String.class, SharedTypeCustomAttribute.class, value);
    }

}
