//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 03:38:01 pm IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demandware.xml.impex.inventory._2007_05_31;
